server:
  port: 9090
spring:
  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/QuizTime
    username: postgres
    password: youcode2023
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
