server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/QuizTime
    username: postgres
    password: youcode2023
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


